export enum CategoryType {
  ThemePark = '테마파크',
  Shop = '쇼핑몰',
  Park = '공원',
  Street = '골목 및 거리',
  Palace = '궁궐',
  Subway = '지하철',
  Village = '마을',
  Christmas = '크리스마스 핫플',
  Hangang = '한강',
  Riverside = '강변',
  Beach = '해변',
  Spring = '봄 나들이',
  Extra = '기타 지역',
}
